
package eu.glowacki.jaxws.client.sorter.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISorter", targetNamespace = "http://glowacki.eu/sorter")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISorter {


    /**
     * 
     * @param arg0
     * @return
     *     returns eu.glowacki.jaxws.client.sorter.proxy.SortResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sortBySurname", targetNamespace = "http://glowacki.eu/sorter", className = "eu.glowacki.jaxws.client.sorter.proxy.SortBySurname")
    @ResponseWrapper(localName = "sortBySurnameResponse", targetNamespace = "http://glowacki.eu/sorter", className = "eu.glowacki.jaxws.client.sorter.proxy.SortBySurnameResponse")
    @Action(input = "http://glowacki.eu/sorter/ISorter/sortBySurnameRequest", output = "http://glowacki.eu/sorter/ISorter/sortBySurnameResponse")
    public SortResponseMessage sortBySurname(
        @WebParam(name = "arg0", targetNamespace = "")
        SortRequestMessage arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns eu.glowacki.jaxws.client.sorter.proxy.SortResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sortByBirthDate", targetNamespace = "http://glowacki.eu/sorter", className = "eu.glowacki.jaxws.client.sorter.proxy.SortByBirthDate")
    @ResponseWrapper(localName = "sortByBirthDateResponse", targetNamespace = "http://glowacki.eu/sorter", className = "eu.glowacki.jaxws.client.sorter.proxy.SortByBirthDateResponse")
    @Action(input = "http://glowacki.eu/sorter/ISorter/sortByBirthDateRequest", output = "http://glowacki.eu/sorter/ISorter/sortByBirthDateResponse")
    public SortResponseMessage sortByBirthDate(
        @WebParam(name = "arg0", targetNamespace = "")
        SortRequestMessage arg0);

}
