
package eu.glowacki.jaxws.client.sorter.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SorterImplService", targetNamespace = "http://glowacki.eu/sorter", wsdlLocation = "http://localhost:8080/sorter?wsdl")
public class SorterImplService
    extends Service
{

    private final static URL SORTERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SORTERIMPLSERVICE_EXCEPTION;
    private final static QName SORTERIMPLSERVICE_QNAME = new QName("http://glowacki.eu/sorter", "SorterImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sorter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SORTERIMPLSERVICE_WSDL_LOCATION = url;
        SORTERIMPLSERVICE_EXCEPTION = e;
    }

    public SorterImplService() {
        super(__getWsdlLocation(), SORTERIMPLSERVICE_QNAME);
    }

    public SorterImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SORTERIMPLSERVICE_QNAME, features);
    }

    public SorterImplService(URL wsdlLocation) {
        super(wsdlLocation, SORTERIMPLSERVICE_QNAME);
    }

    public SorterImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SORTERIMPLSERVICE_QNAME, features);
    }

    public SorterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SorterImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISorter
     */
    @WebEndpoint(name = "ISorterPort")
    public ISorter getISorterPort() {
        return super.getPort(new QName("http://glowacki.eu/sorter", "ISorterPort"), ISorter.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ISorter
     */
    @WebEndpoint(name = "ISorterPort")
    public ISorter getISorterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://glowacki.eu/sorter", "ISorterPort"), ISorter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SORTERIMPLSERVICE_EXCEPTION!= null) {
            throw SORTERIMPLSERVICE_EXCEPTION;
        }
        return SORTERIMPLSERVICE_WSDL_LOCATION;
    }

}
